### ISSUE TITLE
Got exit code 1073741819 (0xC0000005) from python demo

### ISSUE THREAD

**Issue by xinxin8816** [esimov/pigo#58] opened 2022-07-23 14:35 UTC
Hi there,
I try to exec [demo](https://github.com/esimov/pigo/blob/master/examples/facedet/demo.py) with Python 3.9 on Windows, sometimes got unexpected exit, with code -1073741819 (0xC0000005) , that err from C shared lib I think, and that because of index out of range usually.
I'm not good at Golang and not founded the true reason from code, give me some advice to fix it please, thx.

**Comment by esimov** [comment] 2022-07-25 08:40
Can you show me exactly what kind of errors are you getting? Just FYI these demos have been tested on Python2 and OpenCV2 so it might be related to the Python version also on which you are trying to run it.

**Comment by xinxin8816** [comment] 2022-07-25 09:49
Nothing exactly others, just response err code and exit. That err code correlate with out of range in my experience.
Python2 may working well, but Python2 has out of date now.

**Comment by esimov** [comment] 2022-07-25 11:09
I'm aware about that, only that because I have ported the library to WASM I didn't updated the Python examples to run on Python3. But I have tried it with Python3 and OpenCV4 and sometimes just exited without printing any errors. That's why I asked if you could have shown the errors you got.

**Comment by xinxin8816** [comment] 2022-07-25 11:28
<img width="302" alt="image" src="https://user-images.githubusercontent.com/8501725/180766878-17cd08ea-40b6-4ab8-ab6f-840fe6992039.png">
Only got this unuseful message, means:
Process has been exited, exit code is -1073741819 (0xC0000005)

**Comment by esimov** [comment] 2022-07-27 13:44
I have tried on a MacOS with Python 3.9.1 installed and the demos are running, but strangely on Windows in most of the cases the application exits without showing any errors. I was trying to debug it and most probably is related to the data type transfer from Go to Python using ctypes.

**Comment by xinxin8816** [comment] 2022-07-27 14:02
I ran in pycharm with debug mode, and than got exit code. If running in cmd or powershell, that output nothing.

**Comment by esimov** [comment] 2022-11-09 14:04
I'm closing this ticket, the issue is fixed now.

**Closed by esimov** 2022-11-09 14:04 UTC
